name: penny_path
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.1.0
  stacked: ^3.4.1+1
  auto_route: ^7.0.4
  stacked_services: ^1.3.0
  get_it: ^7.6.4
  injectable: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  auto_route_generator: ^7.0.2
  injectable_generator: ^2.4.1

flutter:
  uses-material-design: true
